In [109]:
import torch
import numpy

In [76]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [77]:
a = torch.randn(3, 4, 5)

In [78]:
# 2. Выведите его форму (shape)

In [79]:
a.shape

torch.Size([3, 4, 5])

In [80]:
# 3. Приведите его к форме 6х10

In [81]:
a = a.reshape(-1, 6, 10)
a

tensor([[[ 1.0563,  0.3065,  1.0404,  0.1991, -0.6521, -1.6150, -1.0977,
          -0.4588,  0.9947, -0.7426],
         [ 0.1946,  0.0184, -0.5961, -0.4889,  0.4567,  1.2169,  0.5358,
          -1.8144, -1.4891,  0.8291],
         [ 1.6078, -1.8206, -1.5347, -0.6643,  1.8838, -0.6219, -0.3587,
          -0.9436, -0.4747, -0.3646],
         [-1.6405, -0.0581, -0.9468, -1.2619,  1.0120,  0.4874, -1.9295,
          -1.4005,  0.1381, -0.0364],
         [ 1.2792, -0.6936,  0.8332, -0.3165, -0.4536, -0.4149,  0.5895,
          -1.1522,  2.5046,  2.3156],
         [-1.1322,  0.2384,  0.5384, -0.2009, -1.1847,  0.7338,  0.8658,
           0.0149, -0.7048, -0.2749]]])

In [82]:
# 4. Создайте случайный IntTensor размера 10

In [83]:
b = torch.randint(10, size=(10,))
b

tensor([4, 4, 4, 9, 4, 5, 2, 5, 6, 1])

In [84]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [85]:
c = torch.mul(a, b)
c

tensor([[[  4.2252,   1.2259,   4.1614,   1.7920,  -2.6085,  -8.0748,  -2.1954,
           -2.2939,   5.9684,  -0.7426],
         [  0.7783,   0.0734,  -2.3845,  -4.4003,   1.8270,   6.0846,   1.0715,
           -9.0721,  -8.9347,   0.8291],
         [  6.4310,  -7.2824,  -6.1388,  -5.9788,   7.5351,  -3.1095,  -0.7174,
           -4.7181,  -2.8482,  -0.3646],
         [ -6.5622,  -0.2324,  -3.7872, -11.3572,   4.0478,   2.4371,  -3.8591,
           -7.0023,   0.8287,  -0.0364],
         [  5.1169,  -2.7746,   3.3326,  -2.8483,  -1.8144,  -2.0744,   1.1790,
           -5.7610,  15.0273,   2.3156],
         [ -4.5286,   0.9538,   2.1537,  -1.8082,  -4.7387,   3.6692,   1.7316,
            0.0743,  -4.2286,  -0.2749]]])

In [86]:
c = c.reshape(6, 10)
c.size()

torch.Size([6, 10])

In [87]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [91]:
d = torch.matmul(c, c.T)
d

tensor([[ 158.1436, -103.8101,  -16.8931,  -64.8537,  147.0618,  -58.5159],
        [-103.8101,  229.9867,  107.4437,  128.0610,  -86.3881,   51.7694],
        [ -16.8931,  107.4437,  265.2885,  107.0231,   25.1518,  -75.0439],
        [ -64.8536,  128.0610,  107.0231,  273.3821,   22.5528,   20.9396],
        [ 147.0618,  -86.3881,   25.1518,   22.5528,  326.4573,  -75.0722],
        [ -58.5159,   51.7694,  -75.0439,   20.9396,  -75.0722,   86.2053]])

In [ ]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [100]:
x = torch.tensor(1.0, requires_grad=True) 
z = torch.tensor(0.5, requires_grad=True) 
t = torch.tensor(2.0, requires_grad=True) 

In [102]:
y = x**3 + z - 75*t

In [103]:
y.backward()

In [106]:
x.grad + z.grad + t.grad

tensor(-71.)

In [ ]:
# 8. Создайте единичный тензор размера 5x6

In [111]:
s = torch.ones(5, 6)
s

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [112]:
# 9. Переведите его в формат numpy

In [117]:
!pip install numpy

You should consider upgrading via the 'C:\Users\VOL-WKST1084\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [116]:
s.numpy()

RuntimeError: Numpy is not available